-- =============================================================================
-- ResearchOS - initial schema
--
-- Design notes that matter:
--
--   * Chunk text lives in Postgres; chunk vectors live in Qdrant. Qdrant holds
--     only an id, the vector, and small filterable fields, which keeps its index
--     compact. Postgres is the source of truth for anything we display.
--
--   * Every id is a UUID generated by Postgres (gen_random_uuid). Generating them
--     in the database rather than the app means two writers can never collide,
--     and the id exists before the first INSERT.
--
--   * timestamptz, never timestamp. "timestamp without time zone" silently
--     discards the offset, and a research tool that cannot say WHEN something was
--     indexed cannot answer provenance questions.
--
--   * JSONB, not JSON. JSONB is validated, deduplicated on disk, and indexable.
--     Use it for open-ended attributes that a schema change should not require;
--     use a real column for anything you filter or sort on.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Migration bookkeeping. Applied in filename order, each file exactly once.
CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- documents: one row per ingested source file or URL.
-- -----------------------------------------------------------------------------
CREATE TABLE documents (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    title           TEXT NOT NULL,

    -- pdf | docx | txt | md | url
    source_type     TEXT NOT NULL,

    -- Filesystem path for uploads, canonical URL for web pages.
    source_uri      TEXT NOT NULL,

    -- SHA-256 of the raw bytes. Lets us skip re-ingesting an identical upload
    -- and detect a URL whose content changed since last fetch.
    content_hash    TEXT,

    -- pending | processing | ready | failed
    status          TEXT NOT NULL DEFAULT 'pending',

    -- Populated only when status = 'failed'. Never delete a failed document;
    -- surfacing why ingestion broke is half the point of a research tool.
    error_message   TEXT,

    n_pages         INTEGER,
    n_chars         INTEGER,
    n_chunks        INTEGER,

    -- Open-ended per-source attributes (author, DOI, published_at, ...).
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    indexed_at      TIMESTAMPTZ,

    CONSTRAINT documents_status_valid
        CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
    CONSTRAINT documents_source_type_valid
        CHECK (source_type IN ('pdf', 'docx', 'txt', 'md', 'url'))
);

-- Re-ingesting the same bytes is wasted work, so dedupe on content hash.
-- Partial: only successful ingests participate, so a retry of a failed
-- document is not blocked by its own earlier failed row.
CREATE UNIQUE INDEX documents_content_hash_key
    ON documents (content_hash)
    WHERE content_hash IS NOT NULL AND status = 'ready';

-- The library view filters on status and orders by recency.
CREATE INDEX documents_status_created_idx
    ON documents (status, created_at DESC);

-- GIN lets metadata be queried with @> and ? operators without a full scan.
CREATE INDEX documents_metadata_gin
    ON documents USING GIN (metadata jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- chunks: the retrievable units. One document -> many chunks.
-- -----------------------------------------------------------------------------
CREATE TABLE chunks (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

    -- 0-based position within the document. Preserves reading order, which
    -- matters for reconstructing context and for coherent citation lists.
    chunk_index     INTEGER NOT NULL,

    content         TEXT NOT NULL,

    token_count     INTEGER,

    -- Byte offsets into the *cleaned* document text. Let the UI highlight the
    -- exact source span behind a citation instead of dumping the whole page.
    char_start      INTEGER,
    char_end        INTEGER,

    -- Nullable because not every format has pages.
    page_number     INTEGER,

    -- Nearest heading above this chunk, and the full breadcrumb. "Methods >
    -- Dense Retrieval" tells a reader far more than "chunk 47".
    section_title   TEXT,
    heading_path    TEXT[] NOT NULL DEFAULT '{}',

    -- The Qdrant point id for this chunk's vector. UNIQUE because it is the
    -- join key between the two stores, and duplicates would mean desync.
    qdrant_point_id UUID,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chunks_document_index_unique UNIQUE (document_id, chunk_index),
    CONSTRAINT chunks_qdrant_point_unique UNIQUE (qdrant_point_id),
    CONSTRAINT chunks_chunk_index_nonneg CHECK (chunk_index >= 0),
    -- A zero-length chunk has no embedding worth storing and would be noise on
    -- every single search. Reject it at the schema, not in application code.
    CONSTRAINT chunks_content_nonempty CHECK (length(trim(content)) > 0)
);

-- "Show me the chunks of document X in order" is the single most common query.
CREATE INDEX chunks_document_order_idx
    ON chunks (document_id, chunk_index);

-- Cheap existence check used by the citation verifier, which fetches many
-- chunks at once and needs to confirm each cited id is real.
CREATE INDEX chunks_qdrant_point_lookup
    ON chunks (qdrant_point_id) WHERE qdrant_point_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- ingest_jobs: a database-backed work queue.
--
-- Why a table and not Celery or Redis? A queue you can SELECT FROM is a queue
-- you can debug, inspect, and recover by hand. At this scale a job table plus a
-- polling worker is simpler to operate than a second infrastructure dependency.
-- -----------------------------------------------------------------------------
CREATE TABLE ingest_jobs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

    -- queued | running | done | failed
    status          TEXT NOT NULL DEFAULT 'queued',

    attempts        INTEGER NOT NULL DEFAULT 0,
    max_attempts    INTEGER NOT NULL DEFAULT 3,

    last_error      TEXT,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ,

    -- Set while running. If a worker dies mid-job this timestamp passes, and the
    -- reaper returns the job to 'queued'. Without it, one crashed worker
    -- permanently strands jobs - the classic stuck-queue bug.
    lease_expires_at TIMESTAMPTZ,

    CONSTRAINT ingest_jobs_status_valid
        CHECK (status IN ('queued', 'running', 'done', 'failed')),
    CONSTRAINT ingest_jobs_attempts_nonneg CHECK (attempts >= 0)
);

-- The worker's hot query: oldest queued job, skip anything leased.
CREATE INDEX ingest_jobs_claim_idx
    ON ingest_jobs (status, created_at)
    WHERE status = 'queued';

-- One pending job per document, so a double-click cannot enqueue the same
-- document twice and race two workers against each other.
CREATE UNIQUE INDEX ingest_jobs_one_active_per_document
    ON ingest_jobs (document_id)
    WHERE status IN ('queued', 'running');

-- -----------------------------------------------------------------------------
-- conversations / messages: chat history.
-- -----------------------------------------------------------------------------
CREATE TABLE conversations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title           TEXT NOT NULL DEFAULT 'New conversation',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX conversations_updated_idx
    ON conversations (updated_at DESC);

CREATE TABLE messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,

    -- user | assistant
    role            TEXT NOT NULL,

    content         TEXT NOT NULL,

    -- Per-message retrieval + citation trace. Stored rather than discarded so
    -- you can answer "why did the bot say that?" long after the fact - the
    -- single most useful debugging tool in a RAG system.
    citations       JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT messages_role_valid CHECK (role IN ('user', 'assistant'))
);

CREATE INDEX messages_conversation_order_idx
    ON messages (conversation_id, created_at);

-- -----------------------------------------------------------------------------
-- Evaluation: runs and per-question results.
-- -----------------------------------------------------------------------------
CREATE TABLE eval_runs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,

    -- Frozen copy of every retrieval/embedding setting used. Without this an
    -- eval number is meaningless later: you cannot tell whether a score
    -- changed because the code improved or because a threshold moved.
    config          JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Aggregate metrics for the dashboard.
    summary         JSONB NOT NULL DEFAULT '{}'::jsonb,

    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ
);

CREATE INDEX eval_runs_started_idx ON eval_runs (started_at DESC);

CREATE TABLE eval_results (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id          UUID NOT NULL REFERENCES eval_runs(id) ON DELETE CASCADE,

    question        TEXT NOT NULL,

    -- Document/chunk ids a correct answer must be able to reach.
    expected_sources JSONB NOT NULL DEFAULT '[]'::jsonb,

    retrieved       JSONB NOT NULL DEFAULT '[]'::jsonb,
    answer          TEXT,

    -- recall@k, mrr, ndcg, grounded, citation_precision, ...
    metrics         JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- retrieval_ms, rerank_ms, generation_ms, total_ms
    latencies       JSONB NOT NULL DEFAULT '{}'::jsonb,

    error           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX eval_results_run_idx ON eval_results (run_id);
